
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gaddesurendrakumar/microservices-with-spring
          searchPaths: ConfigData
       
      label: main
server:
  port: 8001
